image: golang:latest

stages:
  - test
  - build
  - deploy

format:
  stage: test
  script:
    - echo "This job tests something"

compile:
  stage: build
  script:
    - echo "Hello, $GITLAB_USER_LOGIN!"

deploy service-env 1/3:
  stage: deploy
  script: echo "Define your deployment script!"
  environment: production

deploy service-env 2/3:
  stage: deploy
  script: echo "Define your deployment script!"
  environment: production

deploy service-env 3/3:
  stage: deploy
  script: echo "Define your deployment script!"
  environment: production